services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: app
    container_name: origins_state_app
    restart: unless-stopped
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: origins_state_db
      DB_USERNAME: root
      DB_PASSWORD: ${DB_PASSWORD}
      CACHE_DRIVER: redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: null
      REDIS_CACHE_DB: 0
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/php.ini:/usr/local/etc/php/conf.d/custom.ini  # Fixed indentation here
    networks:
      app_network_origins_state:
        ipv4_address: 172.28.0.10

  nginx:
    image: nginx:alpine
    container_name: origins_state_nginx
    restart: unless-stopped
    ports:
      - "8081:80"
    depends_on:
      - app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
    networks:
      app_network_origins_state:
        ipv4_address: 172.28.0.30

  db:
    image: mysql:8.0
    # command: --skip-grant-tables
    container_name: origins_state_mysql
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD} # Set MySQL root password here
      MYSQL_DATABASE: origins_state_db # The database Laravel will use
    volumes:
      - db_data:/var/lib/mysql
      # - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      app_network_origins_state:
        ipv4_address: 172.28.0.20

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: origins_state_phpmyadmin
    restart: unless-stopped
    ports:
      - "8091:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
    networks:
      app_network_origins_state:
        ipv4_address: 172.28.0.40

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    networks:
      app_network_origins_state:
        ipv4_address: 172.28.0.60
volumes:
  db_data:


networks:
  app_network_origins_state:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
